import os
from dotenv import load_dotenv
from groq import Groq
from datetime import datetime

# Load environment variables
load_dotenv()

# Initialize Groq client
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if GROQ_API_KEY:
    client = Groq(api_key=GROQ_API_KEY)
else:
    client = None
    print("⚠️ GROQ_API_KEY not set — using local fallback summarizer.")


def summarize_file(file_path: str):
    """
    Summarize a single transcript file and return the result.
    This function is safe to call from the Kafka consumer.
    Returns: dict with title, content, and summary
    """
    if not os.path.exists(file_path):
        print(f"⚠️ File not found: {file_path}")
        return None

    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()

    if not lines:
        print(f"⚠️ Empty file skipped: {os.path.basename(file_path)}")
        return None

    transcript_title = lines[0].strip()
    transcript_text = "".join(lines[1:]).strip()

    print(f"\n🧠 Summarizing: {transcript_title}\n{'=' * 60}")

    prompt = f"""
    Summarize this meeting transcript in a structured documentation format.

    ## Transcript Title:
    {transcript_title}

    ## Transcript:
    {transcript_text}

    Use this format strictly:
    ----------------------------------------
    ## Meeting Summary
    - Overview: [Brief summary]

    ## Key Discussion Points
    - [Topic 1: Details]
    - [Topic 2: Details]

    ## Decisions Made
    - [Decision 1]
    - [Decision 2]

    ## Action Items
    - [Task 1 — Assigned to X, Deadline: Y]

    ## Additional Notes
    - [Extra details, comments, clarifications]
    ----------------------------------------
    """

    try:
        if client is None:
            # fallback summary (for testing without API)
            lines_preview = transcript_text.splitlines()[:6]
            summary_text = (
                "## Meeting Summary\n- Overview: "
                + (lines_preview[0] if lines_preview else "No content")
                + "\n\n## Key Discussion Points\n"
                + "\n".join([f"- {l}" for l in lines_preview[1:4]])
                + "\n\n## Decisions Made\n- None detected\n\n## Action Items\n- None detected\n\n## Additional Notes\n- Generated by local fallback summarizer"
            )
        else:
            response = client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=[
                    {"role": "system", "content": "You are a professional documentation assistant."},
                    {"role": "user", "content": prompt},
                ],
            )
            summary_text = response.choices[0].message.content.strip()

        print(f"\n📝 Summary generated for '{transcript_title}'\n")
        print("=" * 60 + "\n")

        # Return the summary data
        return {
            "title": transcript_title,
            "content": transcript_text,
            "summary": summary_text,
            "timestamp": datetime.now()
        }

    except Exception as e:
        print(f"❌ Error summarizing {os.path.basename(file_path)}: {e}")
        return None


def main():
    """Standalone summary mode (optional)"""
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    DATA_FOLDER = os.path.join(BASE_DIR, "data")

    print(f"📂 Looking for text files in: {os.path.abspath(DATA_FOLDER)}")

    if not os.path.exists(DATA_FOLDER):
        print("⚠️ data folder not found, creating...")
        os.makedirs(DATA_FOLDER)

    text_files = [f for f in os.listdir(DATA_FOLDER) if f.endswith(".txt")]

    if not text_files:
        print("⚠️ No transcript files found in the data folder!")
        return

    for file_name in text_files:
        file_path = os.path.join(DATA_FOLDER, file_name)
        summarize_file(file_path)

    print("🎉 All summaries printed successfully!")


if __name__ == "__main__":
    main()
